-- Deletando tabelas se existirem
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS LIVROS;
DROP TABLE IF EXISTS AUTORES;
DROP TABLE IF EXISTS CLIENTES;

-- Criando a tabela CLIENTES
CREATE TABLE CLIENTES (
    ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL
);

-- Criando a tabela AUTORES
CREATE TABLE AUTORES (
    ID_Autor INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Nacionalidade VARCHAR(100) NOT NULL
);

-- Criando a tabela LIVROS
CREATE TABLE LIVROS (
    ID_Livro INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(255) NOT NULL,
    ID_Autor INT NOT NULL,
    Preco DECIMAL(10, 2) NOT NULL,
    Estoque INT NOT NULL,
    FOREIGN KEY (ID_Autor) REFERENCES AUTORES(ID_Autor) ON DELETE CASCADE
);

-- Criando a tabela PEDIDOS
CREATE TABLE PEDIDOS (
    ID_Pedido INT AUTO_INCREMENT PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    ID_Livro INT NOT NULL,
    Quantidade INT NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Pendente',
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente) ON DELETE CASCADE,
    FOREIGN KEY (ID_Livro) REFERENCES LIVROS(ID_Livro) ON DELETE CASCADE
);
